Repository letscontrolit/ESPEasy, pull requests merged in 2018-03, with the labels that each got.

#983 Added support for degree sign on LCD1602/2004
  src/_P012_LCD.ino
Labels: enhancement, fixed

#1026 [CSS] Quick fix for smaller displays
  src/WebServer.ino
Labels: Category: Frontend

#1027 [issue #1012] Removed Content-Length header + improved webserver speed
  src/WebServer.ino
Labels: Category: Frontend, Type: Enhancement

#1032 [Rule Events] Add a number of events to handle in rules and awake timer
  src/Controller.ino
  src/ESPEasy.ino
  src/Misc.ino
  src/TimeESPeasy.ino
  src/WebServer.ino
  src/Wifi.ino
Labels: Category: Frontend, Type: Enhancement

#1165 [wifi] Event based connect/reconnect
  src/Command.ino
  src/Controller.ino
  src/Convert.ino
  src/ESPEasy-Globals.h
  src/ESPEasy.ino
  src/Misc.ino
  src/Networking.ino
  src/StringConverter.ino
  src/TimeESPeasy.ino
  src/WebServer.ino
  src/Wifi.ino
  src/_C010.ino
  src/_C012.ino
  src/_P036_FrameOLED.ino
Labels: Category: Stabiliy, Type: Enhancement

#1025 Initial re-organisation of plugin sets (#1019)
  src/define_plugin_sets.h
Labels: Category: Build
