Repository letscontrolit/ESPEasy, pull requests merged in 2018-10, with the labels that each got.

#1836 [ESP32] Update to platform espressif32@1.4.0
  esp32_partition_app1310k_spiffs1503k.csv
  platformio.ini
Labels: Category: Build, Platform: ESP32

#1858 [Stack] Increase stack to 5k and reduce stack allocations in rules
  platformio.ini
  src/ESPEasy-Globals.h
  src/Misc.ino
  src/Scheduler.ino
Labels: Category: Stabiliy

#1900 Time#Initialized event in rules before %syshour% is set
  src/TimeESPeasy.ino
Labels: Category: Rules

#1901 [UX] Warn user for incomplete network IP settings
  src/ESPEasy-Globals.h
  src/ESPEasyStorage.ino
Labels: Category: UX

#1914 [#1906] Move Notification and Controller settings to heap
  src/Controller.ino
  src/ESPEasy-Globals.h
  src/Misc.ino
  src/WebServer.ino
  src/_C001.ino
  src/_C002.ino
  src/_C003.ino
  src/_C004.ino
  src/_C005.ino
  src/_C006.ino
  src/_C007.ino
  src/_C008.ino
  src/_C009.ino
  src/_C010.ino
  src/_C011.ino
  src/_C012.ino
  src/_CPlugin_Helper.h
  src/_N001_Email.ino
  src/_N002_Buzzer.ino
  src/_P026_Sysinfo.ino
  src/_P037_MQTTImport.ino
Labels: Category: Stabiliy

#1926 [#1891] Send all values for Generic UDP controller
  src/Controller.ino
  src/_CPlugin_Helper.h
Labels: Category: Controller, Category: Stabiliy, Status: Fixed, Type: Bug

#1943 Bugfix/pubsubclient fixes
  docs/source/WiFi/WiFi.rst
  docs/source/index.rst
  lib/pubsubclient/src/PubSubClient.cpp
  src/Controller.ino
  src/ESPEasy-Globals.h
  src/ESPEasy.ino
  src/Modbus.ino
Labels: Category: Controller, Category: Stabiliy

#1954 [WDT] Replace yield() with delay(0) & add Sonoff POW R2 build
  before_deploy
  platformio.ini
  src/Command.ino
  src/Controller.ino
  src/ESPEasy-Globals.h
  src/ESPEasy.ino
  src/ESPEasyStorage.ino
  src/ESPEasyTimeTypes.h
  src/Misc.ino
  src/Networking.ino
  src/Scheduler.ino
  src/Serial.ino
  src/WebServer.ino
  src/_C012.ino
  src/_CPlugin_Helper.h
  src/_N001_Email.ino
  src/_P079_Wemos_Motorshield.ino
  src/define_plugin_sets.h
Labels: Category: Stabiliy

#1967 [Eastron] Make configurable and allow for multiple values read (#1684)
  lib/SDM_Energy_Meter/README.md
  lib/SDM_Energy_Meter/SDM.cpp
  lib/SDM_Energy_Meter/SDM.h
  src/_P078_Eastron.ino
Labels: Category: Plugin

#1968 [NTP] Improve NTP accuracy
  src/TimeESPeasy.ino
Labels: Type: Enhancement

#1619 Added Special Case to allow Servo to be disabled
  src/_P001_Switch.ino
Labels: Category: Plugin, Type: Enhancement
