Repository letscontrolit/ESPEasy, pull requests merged in 2018-09, with the labels that each got.

#1686 [Pio] Build issue P016_IR and add PIO flags
  platformio.ini
  src/_P016_IR.ino
Labels: Category: Build

#1694 [#1692] Add 2nd Receiver for Email notification
  src/_N001_Email.ino
Labels: Type: Enhancement

#1695 [#1549] Add page showing all system variables
  src/WebServer.ino
  src/WebStaticData.h
Labels: Category: Frontend, Type: Feature Request

#1700 [Shelly1] Add first test build for Shelly1 nodes
  before_deploy
  platformio.ini
  src/define_plugin_sets.h
Labels: Category: Build

#1669 Use queue to manage controllers and add timing settings per controller
  src/Commands/Common.h
  src/Commands/HTTP.h
  src/Controller.ino
  src/ESPEasy-Globals.h
  src/ESPEasy.ino
  src/ESPEasyWifi.ino
  src/Misc.ino
  src/Networking.ino
  src/Scheduler.ino
  src/WebServer.ino
  src/WebStaticData.h
  src/_C001.ino
  src/_C002.ino
  src/_C003.ino
  src/_C004.ino
  src/_C005.ino
  src/_C006.ino
  src/_C007.ino
  src/_C008.ino
  src/_C009.ino
  src/_C010.ino
  src/_C011.ino
  src/_C012.ino
  src/_C013.ino
  src/_CPlugin_Helper.h
  src/_N001_Email.ino
  src/__CPlugin.ino
  src/__Plugin.ino
Labels: Category: Controller, Category: Stabiliy, Type: Enhancement

#1721 [#1720] WiFi read all lines from slow servers
  src/ESPEasy-Globals.h
  src/ESPEasy.ino
  src/Misc.ino
  src/_C003.ino
  src/_C012.ino
  src/_CPlugin_Helper.h
Labels: Category: Controller, Category: Stabiliy, Category: Wifi

#1727 Reduced buffer size to prevent stack overflow
  src/_P044_P1WifiGateway.ino
Labels: Category: Plugin, Category: Stabiliy, Type: Bug

#1730 Feature: Split webserver spiffs filelist into pages
  src/WebServer.ino
Labels: Category: UX, Type: Feature Request

#1731 Use parameters inside rules when calling commands
  src/Command.ino
  src/Misc.ino
Labels: Category: Rules, Category: UX, Type: Enhancement

#1740 [CrashRecover] Disable failing step based on failed boot count
  src/ESPEasy-Globals.h
  src/ESPEasy.ino
  src/ESPEasyStorage.ino
Labels: Category: Stabiliy, Category: UX

#1641 Fix elseif & Add if-elseif-else nesting levels
  .gitignore
  src/ESPEasy-Globals.h
  src/Misc.ino
Labels: Category: Rules, Type: Enhancement

#1777 [MQTT import] Fix crash at boot when plugin is enabled
  src/_P037_MQTTImport.ino
Labels: Category: Stabiliy, Type: Bug

#1779 [BME280] Fix slow reading of BME280 causing watchdog resets
  src/_P028_BME280.ino
Labels: Category: Plugin, Category: Stabiliy, Type: Bug

#1782 [MQTT] Work around for lost MQTT connection
  src/Controller.ino
Labels: Category: Controller, Category: Stabiliy
