Repository letscontrolit/ESPEasy, pull requests merged in 2019-01, with the labels that each got.

#2213 [WiFi] Some basic fixes to improve wifi reconnect
  src/ESPEasyWifi.ino
Labels: Category: Stabiliy, Category: Wifi

#2217 [deepSleep] Make deepSleep work again with 2.5.0 and refactor delay var
  src/Misc.ino
  src/WebServer.ino
Labels: Category: Energy, Category: Stabiliy

#2239 [WiFi] Disable wifi initialization at boot (core 2.5.0-b2)
  src/ESPEasy.ino
Labels: Category: Stabiliy, Category: Wifi

#2231 [IRTX] mitsubishi_ac not working #2230
  src/_P035_IRTX.ino
Labels: Type: Bug
