Repository letscontrolit/ESPEasy, pull requests merged in 2020-05, with the labels that each got.

#3042 [Bugfix] PVS Studio issues
  .travis.yml
  lib/ccronexpr/ccronexpr.h
  lib/esp8266-oled-ssd1306/OLEDDisplay.h
  lib/esp8266-oled-ssd1306/OLEDDisplayFonts.h
  platformio_core_defs.ini
  platformio_esp82xx_base.ini
  platformio_esp82xx_envs.ini
  pre_custom_esp82xx.py
  src/ESPEasyRules.ino
  src/Misc.ino
  src/Networking.ino
  src/Scheduler.ino
  src/StringConverter.ino
  src/WebServer_Rules.h
  src/_C018.ino
  src/_P028_BME280.ino
  src/_P036_FrameOLED.ino
  src/_P052_SenseAir.ino
  src/_P081_Cron.ino
  src/_P095_ILI9341.ino
  src/_Plugin_Helper_serial.ino
  src/src/Commands/Diagnostic.cpp
  src/src/DataStructs/ESPEasy_EventStruct.cpp
  src/src/DataStructs/ESPEasy_EventStruct.h
  src/src/DataStructs/RTCStruct.h
  src/src/DataStructs/SecurityStruct.h
  src/src/Helpers/ESPEasy_time.cpp
  src/src/Helpers/ESPEasy_time.h
  src/src/Helpers/SystemVariables.cpp
  src/src/Helpers/msecTimerHandlerStruct.cpp
  src/src/PluginStructs/P087_data_struct.cpp
  src/src/PluginStructs/P094_data_struct.cpp
  src/src/Static/WebStaticData.h
Labels: Category: PVS-studio

#3048 [PIO] Generate filename at build, not in post processing
  .gitignore
  .travis.yml
  before_deploy
  dist/README.txt
  docs/requirements.txt
  docs/source/Participate/ProjectStructure.rst
  docs/source/_static/css/custom.css
  platformio.ini
  platformio_core_defs.ini
  platformio_esp32_envs.ini
  platformio_esp82xx_envs.ini
  platformio_special_envs.ini
  requirements.txt
  src/ESPEasy-Globals.h
  src/Hardware.ino
  src/StringProvider.ino
  src/StringProviderTypes.h
  src/WebServer_SysInfoPage.ino
  src/_CPlugin_Helper.cpp
  src/_P076_HLW8012.ino
  src/define_plugin_sets.h
  src/src/DataStructs/DeviceModel.h
  src/src/Helpers/CompiletimeDefines.cpp
  src/src/Helpers/CompiletimeDefines.h
  src/src/Helpers/SystemVariables.cpp
  tools/build_ESPeasy.sh
  tools/pio/copy_files.py
  tools/pio/generate-compiletime-defines.py
  tools/pio/gzip-firmware.py
  tools/pio/post_esp32.py
  tools/pio/pre_custom_esp32.py
  tools/pio/pre_custom_esp82xx.py
  tools/pio/pre_default_check.py
  tools/pio/pre_memanalyze.py
  tools/vagrant/Vagrantfile
  tools/vagrant/bootstrap.sh
Labels: Category: Build

#3063 Fix ESP32 undefined pin initialisation
  src/Hardware.ino
Labels: Platform: ESP32, Type: Bug
